title: FlashSpeak
email: dv.denstr@gmail.com
description: Создавай карточки с иностранными словами и изучай язык
copyright: Copyright © 2023 Denis Dmitriev.
domain: dendmitriev.github.io/Flashspeak/ 
baseurl: /Flashspeak/ # the subpath of your site, e.g. /blog
url: https://dendmitriev.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: DenDmitriev
appstore: /images/download-on-the-app-store.svg

banner-image: /images/bannerImage.png

# Menu
show_menu: true
home: /
support: /Support/
privacy-policy: /PrivacyPolicy/

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed

# Languages jekyll-multiple-languages-plugin settings:
languages: ["en", "ru", "de", "fr", "es", "pt"]
exclude_from_localizations: [images", "assets"]
# default_locale_in_subfolder: true
